
fragment:
    material:
        m.shading_model = SHADING_MODEL_CLEARCOAT;
        m.basecolor = texture(p3d_Texture0, texcoord).xyz;
        m.roughness = 0.4;
        m.specular_ior = 0.5;
        m.metallic = 0.5;
        m.normal = vOutput.normal;
        m.shading_model_param0 = 0.0; // unused
